### ISSUE TITLE
通过GitHub的actions build会出现node本版过高导致的new _Hash错误，ubuntu last用的node是 v18.16.0

### ISSUE THREAD

**Issue by lucianLF** [xjh22222228/nav#236]
### Version
6.0.1

### Reproduction link
[https://github.com/lucianLF/nav/actions/runs/4899549535/jobs/8749586949](https://github.com/lucianLF/nav/actions/runs/4899549535/jobs/8749586949)

### Steps to reproduce
```
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/runner/work/nav/nav/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:172:11
    at loadLoader (/home/runner/work/nav/nav/node_modules/loader-runner/lib/loadLoader.js:32:11)
    at iteratePitchingLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/runner/work/nav/nav/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/home/runner/work/nav/nav/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:739:10)
    at /home/runner/work/nav/nav/node_modules/webpack/lib/Compilation.js:1111:12
    at /home/runner/work/nav/nav/node_modules/webpack/lib/NormalModuleFactory.js:409:6 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
Error: Process completed with exit code 1.
```

### What is expected?
build success

### What is actually happening?
Error: Process completed with exit code 1.

**Comment by lucianLF** [comment]
改ci吧

**Comment by aiyou9** [comment]
确实，现在github action的nodejs 版本升级了，项目也得升级
