### ISSUE TITLE
打包问题报错

### ISSUE THREAD

**Issue by linpingchuan** [xjh22222228/nav#52]
node环境版本： v10.23.3
操作系统： Ubuntu20 或者 Windows10
在执行npm run build命令时，提示以下错误，目前不知道如何解决
```shell
> nav@5.2.0 build /tmp/nav
> npm run setup && ng build --prod --base-href ./


> nav@5.2.0 setup /tmp/nav
> tsc nav.config.ts && ts-node ./scripts/build.mjs
lin@ubuntu-home:/tmp/nav$ npm run build

> nav@5.2.0 build /tmp/nav
> npm run setup && ng build --prod --base-href ./


> nav@5.2.0 setup /tmp/nav
> tsc nav.config.ts && ts-node ./scripts/build.mjs

/tmp/nav/scripts/build.mjs:4
import fs from 'fs'
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at Object.<anonymous> (/tmp/nav/node_modules/ts-node/src/bin.ts:158:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nav@5.2.0 setup: `tsc nav.config.ts && ts-node ./scripts/build.mjs`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nav@5.2.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lin/.npm/_logs/2021-02-11T03_23_44_702Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nav@5.2.0 build: `npm run setup && ng build --prod --base-href ./`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nav@5.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lin/.npm/_logs/2021-02-11T03_23_44_715Z-debug.log
```

**Comment by xjh22222228** [comment]
尝试使用node >= 14， 另外本地不需要打包呀，打包做什么用。
